name: Deploy Lambda Function

on:
  push:
    paths:
      - "**.py"
      - "src/**"
      - "function/**"
      - "config/**"
      - "package/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Create Zip file for Lambda function
        run: |
          zip -r code.zip src/ config/ package/ function/

      - name: List src directory contents for debugging
        run: ls -la src/

      - name: AWS CLI V2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:eu-north-1:779846800085:function:ai-content-creator
            --zip-file fileb://code.zip

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          MIDJOURNEY_API_KEY: ${{ secrets.MIDJOURNEY_API_KEY }}

